### PR TITLE
Changes to UI elements & Live Activities

### PR DESCRIPTION
**Pull request by lumaa-dev**
Added:
- "Scan the Cider QR code" when `QRScannerView` is showed
- the blurred artwork of the current song playing (when there's no song playing, it's a simple gray linear gradient)
- a proper dark and tinted icon
- haptics to the *Refresh Interval* setting 

Changed:
- the appearance of the *Button Size* and *Album Art Size* settings pickers
- size of song title and artist labels (also in `LyricsView`)
- background for the `LyricsView` and the `QueueView` for clearer one
- `LyricsView` for better lyrics viewing
  - Instead of changing the font size and weight, change the view size
- a lot of deprecated APIs for stable ones (still a lot needs to be done)
- the file organisation because everything in `ContentView.swift` and `MusicPlayerView.swift` isn't very ethical

### CODE REVIEW

**Comment by lumaa-dev** [comment]
Added:
- a Live Activity when a song plays
- a *Playback Notification* setting in the Settings
- the [Now Playing](https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter) code but it does not work

Changed:
- more project organisation

**Comment by lumaa-dev** [comment]
image!

**Comment by cryptofyre** [comment]
Nice work, will look more deeply into this PR a little later.

**Comment by cryptofyre** [comment]
So far everything looks good, I did notice the live activity doesn't show any information when hard pressed on in the dynamic island.

Is that intentional?

**Comment by lumaa-dev** [comment]
> So far everything looks good, I did notice the live activity doesn't show any information when hard pressed on in the dynamic island.
> 
> Is that intentional?

Surely not, I don't have a device with one so I couldn't try it out

**Comment by lumaa-dev** [comment]
> image

One issue with this seems to be like the Live Activity doesn't update when the song plays while the app is in the background. This could easily be fixed with the [`Background Tasks` framework](https://developer.apple.com/documentation/backgroundtasks)

**Comment by GottaLoveAng** [comment]
any update on this being merged into the app?

**Comment by lumaa-dev** [comment]
> any update on this being merged into the app?

Good question

**Review by cryptofyre — APPROVED** [review]

**Pull request merged**
